name: Deploy project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Zip project directory
        run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf deploy.tar ../build/

      - name: Copy project zip to AWS via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER_NAME }}
          key: ${{ secrets.AWS_PASSWORD }}
          source: "deploy.tar"
          target: "/home/ubuntu/"

      - name: docker-compose in AWS
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER_NAME }}
          key: ${{ secrets.AWS_PASSWORD }}
          script: |
            cd ./build
            sudo docker-compose down
            cd ..
            rm -rf ./build
            tar -xvf deploy.tar
            rm -rf ./deploy.tar
            cd ./build
            sudo docker-compose up -d --build
